#!/bin/bash
# Zestfile
#
# This file contains all the definitions and scripts needed to build
# and test each component of your project.

# DOCKER_FILE
# This will allow you to override the default location for the Dockerfile
# which is otherwise assumed to be ./Dockerfile
DOCKER_FILE=

# BUILD_CONTAINER (required for build command)
# Specify a container to build your application in
# In [repo/]image[:tag] format
BUILD_CONTAINER=golang:1.7

# TEST_CONTAINER (required if BUILD_CONTAINER not specified)
# The container to put your application in to launch tests
# In [repo/]image[:tag] format
TEST_CONTAINER=

# REPO
# The name of the project repo that the resulting image from a bundle will be tagged as
# Defaults to the parent directory name (../)
REPO=example

# The name of the service that the resulting image from a bundle will be tagged as
# Defaults to the current directory name (./)
SERVICE_NAME=

# IMAGE_SERVER
# The remote server to send the docker images to
IMAGE_SERVER=

# VERSION
# For statically versioned projets, this can be any string
# This setting will be overridden by any output from Version() below
VERSION=0.1.0

# MOUNT_DIR
# Specifies where the project code will be mounted in the BUILD_CONTAINER
# and TEST_CONTAINER, for building and testing respectively
# Will be mounted at $MOUNT_DIR/<service-name>
MOUNT_DIR=

# CACHE_DIR_SRCS
# CACHE_DIR_DSTS
# Additional mounts for cached code, modules, or assets
CACHE_DIR_SRCS=()
CACHE_DIR_DSTS=()

# PreBuild()
# The script to be executed outside of the build container (local machine)
# before the build step
PreBuild() {
	# ex:
	# cat stuff > settings.xml
	:
}

# PostBuild()
# The script to be executed outside of the build container (local machine)
# after the build step.
PostBuild() {
	# ex:
	# cleanup.sh
	:
}

# Build()
# The script to be executed inside BUILD_CONTAINER in the project directory
# to build any assets or binaries
Build() {
	# ex:
	# go build
	# rake
	# bundle
	# npm install
	CGO_ENABLED=0 go build -v
}

# Test()
# The script to be executed inside TEST_CONTAINER in the projecte directory
# to perform any unit tests for the application
Test() {
	# ex:
	# go test
	# npm test
	:
}

# Version()
# For more dynamic versioning, this function will override the VERSION config
# Use this to generate a version number uniquely for each commit or build
Version() {
	# ex:
	# git describe --tags
	:
}

# PreBundle()
# The script to be executed outside of the build container (local machine)
# before the bundle step
PreBundle() {
	# ex:
	# cat stuff > settings.xml
	:
}

# PostBundle()
# The script to be executed outside of the build container (local machine)
# after the build step.
PostBundle() {
	# ex:
	# rm settings.xml
	:
}
